version: "3.8"
services: 
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server
    restart: always
    ports:
      - 80:80
#    volumes: 
#      - ./html:/var/www/html
#volumes:
#  html: {}
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sample'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sampleuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'samplepass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'samplepass'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: {}